name: sunmi_thermal_printer_example
description: Demonstrates how to use the sunmi_thermal_printer plugin.
publish_to: "none"

version: 1.0.0+9

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
 
  flutter_chat_bubble: ^1.0.2
  socket_io_client: ^0.9.12
  socket_io: ^0.9.4
  web_socket_channel: "1.1.0"
  lottie: "0.3.0"
  firebase_core: "0.7.0"
  firebase_messaging: "^8.0.0-dev.14"
  # connectivity: ^2.0.2
  image: ^2.1.19
  url_launcher: ^5.7.10
  flutter_barcode_scanner: ^1.0.1
  geolocator: ^6.1.7
  google_maps_flutter: ^1.0.6
  shared_preferences: ^0.5.6+2
  http: ^0.12.0+4
  flutter:
    sdk: flutter
  intl: ^0.16.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/rayaicon.png"
  
dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  


  # sunmi_thermal_printer:
  #   path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
